name: Node.js Continuous Integration

on:
  push:
    branches-ignore:
      - "main"
  pull_request:
    branches-ignore:
      - "main"

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "15.x"

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      - name: Test
        run: npm run test:ci

        env:
          CI: true
